<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>async/await实现</title>
</head>

<body>
  <!-- <script>
    function run(gen) {
      //把返回值包装成promise
      return new Promise((resolve, reject) => {
        var g = gen()

        function step(val) {
          //错误处理
          try {
            var res = g.next(val)
          } catch (err) {
            return reject(err);
          }
          if (res.done) {
            return resolve(res.value);
          }
          //res.value包装为promise，以兼容yield后面跟基本类型的情况
          Promise.resolve(res.value).then(
            val => {
              step(val);
            },
            err => {
              //抛出错误
              g.throw(err)
            });
        }
        step();
      });
    }

    function* myGenerator() {
      try {
        let data = yield Promise.resolve('data')
        console.log(data)

        console.log(yield Promise.resolve(1))

        console.log(yield 2) //2
        console.log(yield Promise.reject('error'))
      } catch (error) {
        console.log(error)
      }
    }

    const result = run(myGenerator) //result是一个Promise
    //输出 1 2 error

  </script> -->

  <!-- <script>
    function asyncToGen(genFunction) {
      return function (...args) {
        const gen = genFunction.apply(this, args);
        return new Promise((resolve, reject) => {
          function step( arg) {
            let genResult;
            try {
              genResult = gen.next(arg);
              console.log(genResult)
            } catch (err) {
              return reject(err);
            }
            const {
              value,
              done
            } = genResult;
            if (done) {
              return resolve(value);
            }
            return Promise.resolve(value).then(
              (val) => {
                step( val);
              },
              (err) => {
                step( err);
              },
            );
          }
          step();
        });
      };
    }
    const getData = () => new Promise(resolve => setTimeout(() => resolve('data'), 1000));

    function* testG() {
      const data = yield getData();
      console.log('data: ', data);
      const data2 = yield getData();
      console.log('data2: ', data2);
      return 'success';
    }

    const gen = asyncToGen(testG);
    gen().then(res => console.log(res));

  </script> -->


  <script>
    function asyncToGen(testG) {
      return function (...args) {
        let gen = testG.call(this, ...args)
        return new Promise((resolve, reject) => {
          function step(arg) {
            let res
            try {
              res = gen.next(arg)
              console.log(res)
            } catch (e) {
              reject(e)
            }
            const { value, done } = res
            if (done) {
              return resolve(value)
            }
            return Promise.resolve(value).then(res => {
              step(res)
            }).catch(err => {
              step(err)
            })
          }
          step()
        })
      }

    }

    const getData1 = () => new Promise(resolve => setTimeout(() => resolve('data1'), 1000));
    const getData2 = () => new Promise(resolve => setTimeout(() => resolve('data2'), 1000));

    function* testG() {
      const data1 = yield getData1()
      console.log(data1)
      const data2 = yield getData2()
      console.log(data2)
      return 'success'
    }

    let gen = asyncToGen(testG)
    gen().then(res => {
      console.log(res)
    })
  </script>
</body>

</html>